[package]
name = "ext4_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbg_hex = "0.1.1"
libc = "0.2.142"
